cc_library(
    name = "core",
    srcs = glob(
        [
            "lib/core/*.cc",
        ],
        exclude = [
            "lib/core/*_Windows.cc",
            "lib/core/*_MacOSX.cc",
        ],
    ),
    hdrs = glob([
        "include/core/*.h",
        "3rd_party/include/rapidxml/*.hpp",
        "3rd_party/rapidjson/include/rapidjson/**/*.h",
    ]),
    copts = [
        "-std=gnu++14",
        "-g",
        "-O3",
        "-Wdisabled-optimization",
        "-msse4.2",
        "-mfpmath=sse",
        "-fstack-protector",
        "-fno-math-errno",
        "-fno-permissive",
        "-Wall",
        "-Wcast-align",
        "-Wconversion",
        "-Wextra",
        "-Winit-self",
        "-Wparentheses",
        "-Wpointer-arith",
        "-Wswitch-enum",
        "-Wno-ctor-dtor-privacy",
        "-Wno-deprecated-declarations",
        "-Wold-style-cast",
        "-fvisibility-inlines-hidden",
        "-fPIC",
        "-DLinux",
        "-DLINUX=2",
        "-D_REENTRANT",
        "-DNDEBUG",
        "-DEXCLUDE_TRACE_LOGGING",
        "-D_FORTIFY_SOURCE=2",
        "-DDYNAMIC_LIB_EXT=.so",
        "-DBOOST_MATH_NO_LONG_DOUBLE_MATH_FUNCTIONS",
        "-DRAPIDJSON_HAS_STDSTRING",
        "-DRAPIDJSON_SSE42",
        "-I/usr/local/gcc73/include/libxml2",
        "-isystem",
        "/usr/local/gcc73/include/boost-1_65_1",
    ],
    includes = [
        "3rd_party/include",
        "3rd_party/rapidjson/include",
        "include",
    ],
    visibility = ["//visibility:public"],
)
